import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner =
  "/* Generated by esbuild. See repository sources for editable code. */";
const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  sourcemap: production ? false : "inline",
  target: "es2020",
  treeShaking: true,
});

if (production) {
  await context.rebuild();
  process.exit(0);
}

await context.watch();
