import esbuild from "esbuild";
import { copyFileSync, mkdirSync } from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";
import process from "node:process";

const banner =
  "/* Generated by esbuild. See repository sources for editable code. */";
const production = process.argv[2] === "production";

// Copy the built plugin into the in-repo manual-test vault after each build so
// `npm run dev` / `npm run build` keep the vault's plugin in sync. The vault
// lives at test-vault/ (see test-vault/README.md).
const testVaultPluginDir = path.join(
  "test-vault",
  ".obsidian",
  "plugins",
  "flashcards-obsidian",
);
const copyToTestVault = {
  name: "copy-to-test-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      mkdirSync(testVaultPluginDir, { recursive: true });
      copyFileSync("main.js", path.join(testVaultPluginDir, "main.js"));
      copyFileSync(
        "manifest.json",
        path.join(testVaultPluginDir, "manifest.json"),
      );
      copyFileSync("styles.css", path.join(testVaultPluginDir, "styles.css"));
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  plugins: [copyToTestVault],
  sourcemap: production ? false : "inline",
  target: "es2020",
  treeShaking: true,
});

if (production) {
  await context.rebuild();
  process.exit(0);
}

await context.watch();
