name: Checks

on:
  pull_request:
  push:
    branches:
      - main
      - rewrite-v2

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Run checks
        run: npm run check
